## Вычисления с помощью Numpy

### Задание 1

In [1]:
import numpy as np

In [2]:
a = np.array ([[1, 6],
              [2, 8],
              [3, 11],
              [3,10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Задание 2

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [5]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [6]:
a_centered_sp / (a.shape[0] - 1)

2.0

### Задание 4

In [7]:
np.cov(a.T)[0, 1]

2.0

## Работа с данными в Pandas

### Задание 1

In [8]:
import pandas as pd

In [9]:
authors = pd.DataFrame({
    "authors_id" : [1, 2, 3],
    "author_name" : ["Тургенев", "Чехов", "Островский"]
})
authors

authors_id author_name
0           1    Тургенев
1           2       Чехов
2           3  Островский

In [10]:
book = pd.DataFrame({
    "authors_id" : [1, 1, 1, 2, 2, 3, 3],
    "book_title" : ["Отцы и дети", "Рудин", "Дворянское гнездо", "Толстый и тонкий", "Дама с собачкой", "Гроза", "Таланты и поклонники"],
    "price" : [450, 300, 350, 500, 450, 370, 290]
})
book

authors_id            book_title  price
0           1           Отцы и дети    450
1           1                 Рудин    300
2           1     Дворянское гнездо    350
3           2      Толстый и тонкий    500
4           2       Дама с собачкой    450
5           3                 Гроза    370
6           3  Таланты и поклонники    290

### Задание 2

In [11]:
authors_price = pd.merge(authors, book, on = "authors_id", how = "inner")
authors_price

authors_id author_name            book_title  price
0           1    Тургенев           Отцы и дети    450
1           1    Тургенев                 Рудин    300
2           1    Тургенев     Дворянское гнездо    350
3           2       Чехов      Толстый и тонкий    500
4           2       Чехов       Дама с собачкой    450
5           3  Островский                 Гроза    370
6           3  Островский  Таланты и поклонники    290

### Задание 3

In [12]:
top5 = authors_price.nlargest(5, "price")
top5

authors_id author_name         book_title  price
3           2       Чехов   Толстый и тонкий    500
0           1    Тургенев        Отцы и дети    450
4           2       Чехов    Дама с собачкой    450
5           3  Островский              Гроза    370
2           1    Тургенев  Дворянское гнездо    350

### Задание 4

In [13]:
authors_stat1 = authors_price.groupby("author_name").agg({"price" : "min"})
authors_stat1

price
author_name       
Островский     290
Тургенев       300
Чехов          450

In [14]:
authors_stat1 = authors_stat1.rename(columns = {"price" : "min_price"})
authors_stat1

min_price
author_name           
Островский         290
Тургенев           300
Чехов              450

In [15]:
authors_stat2 = authors_price.groupby("author_name").agg({"price" : "max"})
authors_stat2

price
author_name       
Островский     370
Тургенев       450
Чехов          500

In [16]:
authors_stat2 = authors_stat2.rename(columns = {"price" : "max_price"})
authors_stat2

max_price
author_name           
Островский         370
Тургенев           450
Чехов              500

In [17]:
authors_stat3 = authors_price.groupby("author_name").agg({"price" : "mean"})
authors_stat3

price
author_name            
Островский   330.000000
Тургенев     366.666667
Чехов        475.000000

In [18]:
authors_stat3 = authors_stat3.rename(columns = {"price" : "mean_price"})
authors_stat3

mean_price
author_name            
Островский   330.000000
Тургенев     366.666667
Чехов        475.000000

In [19]:
authors_stat = pd.merge(authors_stat1, authors_stat2, on = "author_name", how = "inner")
authors_stat = pd.merge(authors_stat, authors_stat3, on = "author_name", how = "inner")
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

### Задание 5

In [20]:
authors_price["cover"] = ["твердая", "мягкая", "мягкая", "твердая", "твердая", "мягкая", "мягкая"]
authors_price

authors_id author_name            book_title  price    cover
0           1    Тургенев           Отцы и дети    450  твердая
1           1    Тургенев                 Рудин    300   мягкая
2           1    Тургенев     Дворянское гнездо    350   мягкая
3           2       Чехов      Толстый и тонкий    500  твердая
4           2       Чехов       Дама с собачкой    450  твердая
5           3  Островский                 Гроза    370   мягкая
6           3  Островский  Таланты и поклонники    290   мягкая